### PR TITLE
add secure entry with eye icons to password/confirmPassword textFields, WIP

### PR DESCRIPTION
**Pull request by alvare52**
# Description

Fixes non-secure password textfields

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks great.

**Review by ladybeitel — CHANGES_REQUESTED** [review]
Please remove unnecessary comments.

**Comment by ladybeitel** [comment]
Thanks for deleting those! Great job!

**Comment by ladybeitel** [comment]
[Sign Up/Sign In](https://trello.com/c/jw49RpdO/64-sign-up-sign-in)

**Pull request merged**
