### PR TITLE
Feature/forgot password

### PR DESCRIPTION
**Pull request by ladybeitel**
# Description

Implements forgot password feature.
Trello card: https://trello.com/c/70FssAp8/113-endpoints-for-forgot-password

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Change Status
- [x] Complete, tested, ready to review and merge

## How Has This Been Tested?
- [x] Manually tested with simulator (iPhone 11)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by ladybeitel** [comment]
[Endpoints for Forgot Password](https://trello.com/c/70FssAp8/113-endpoints-for-forgot-password)

**Review by ghost — COMMENTED** [review]
great job CC.

**Review by alvare52 — CHANGES_REQUESTED** [review]
mayhaps add a "skip" button that lets users (and more importantly me) to test out other features without having to sign up (like searching for a book)

**Comment by ladybeitel** [comment]
@alvare52  Changes made in last commit. Please review.

**Review by alvare52 — APPROVED** [review]

**Pull request merged**
