### PR TITLE
Feature/star rating view

### PR DESCRIPTION
**Pull request by alvare52**
# Description

Fixes Bug #3 Star rating not showing correct rating
Trello card: https://trello.com/c/ZfjyNvQP/104-bug-3-star-rating-not-showing-correct-rating

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Change Status
- [x] Complete, tested, ready to review and merge

## How Has This Been Tested?
- [x] Manually tested with simulator (iPhone 11 Pro Max)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
great job.

**Comment by alvare52** [comment]
[Bug #3 Star rating not showing correct rating](https://trello.com/c/ZfjyNvQP/104-bug-3-star-rating-not-showing-correct-rating)

**Review by ladybeitel — APPROVED** [review]
Great work on the switch statement!

**Comment by ladybeitel** [comment]
[Search](https://trello.com/c/maOn01aG/65-search)

**Comment by ladybeitel** [comment]
[Search](https://trello.com/c/maOn01aG/65-search)

**Pull request merged**
